# Generated by Django 5.0.6 on 2024-06-22 16:56

import apps.home.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('referal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('admin', 'admin'), ('employee', 'employee'), ('cluster', 'cluster')], default='admin', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', apps.home.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopowner_number', models.CharField(default='', max_length=255, unique=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_type', models.CharField(blank=True, choices=[('panshop', 'pan shop'), ('teashop', 'tea shop'), ('hosptial', 'hosptial'), ('restrant', 'restrant')], default='', max_length=100, null=True)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('points', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('rcb_agreed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PickupTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_bags', models.BooleanField(default=True)),
                ('lifted_status', models.BooleanField(default=True)),
                ('total_pointes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_waste_type', to=settings.AUTH_USER_MODEL)),
                ('shop_owner', models.ForeignKey(db_column='shop_owner_id', on_delete=django.db.models.deletion.DO_NOTHING, to='home.shopowner')),
            ],
            options={
                'db_table': 'pickup_transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastename', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_images/')),
                ('quantity', models.CharField(default='kg', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='waste_type', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waste_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PickupWastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('pointes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pickup_transaction', models.ForeignKey(db_column='pickup_transaction_id', on_delete=django.db.models.deletion.DO_NOTHING, to='home.pickuptransaction')),
                ('waste_type', models.ForeignKey(db_column='waste_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='home.wastetype')),
            ],
            options={
                'db_table': 'pickup_waste_data',
                'managed': True,
            },
        ),
    ]
