# Generated by Django 5.0.6 on 2024-06-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuptransaction',
            name='total_pointes',
        ),
        migrations.AddField(
            model_name='pickupwastdata',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
