# Generated by Django 5.1.4 on 2025-06-21 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_marketupdate_dailymarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('price_2pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_3pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_4pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_5pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_6pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_7pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_8pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_9pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_10pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_11pm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyMarket',
        ),
        migrations.DeleteModel(
            name='MarketUpdate',
        ),
    ]
