# Generated by Django 5.0.6 on 2024-06-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_pickuptransaction_total_pointes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickupwastdata',
            old_name='pointes',
            new_name='price',
        ),
    ]
