# Generated by Django 5.1.4 on 2025-06-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_marketcoin_delete_dailymarket_delete_marketupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketcoin',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketcoin',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
