# Generated by Django 5.0.6 on 2024-06-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_pickupwastdata_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clusteraera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_aera', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cluster_aera',
                'managed': True,
            },
        ),
    ]
