# Generated by Django 5.0.6 on 2024-07-09 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pickuptransaction_cluser_aera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuptransaction',
            name='cluser_aera',
            field=models.ForeignKey(db_column='cluster_aera', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cluster_transaction', to='home.clusteraera'),
        ),
    ]
