# Generated by Django 5.0.6 on 2024-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_pickuptransaction_cluser_aera'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptransaction',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
