# Generated by Django 5.0.6 on 2024-07-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pickuptransaction_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptransaction',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
